name: Analyze smart contracts

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Slither static analyser
        uses: crytic/slither-action@v0.3.0
        continue-on-error: true
        with:
          node-version: ${{ matrix.node_version }}
          target: 'contracts/src/Racer.sol'
